#!/usr/bin/env bash
# =============================================================================
# update_repo.sh
# Run from inside your llm-formal-reasoning/ folder on Mac.
# Downloads the updated files and commits them.
# Usage: bash update_repo.sh
# =============================================================================
set -euo pipefail

echo "Checking we're in the right folder..."
if [ ! -f "README.md" ] || [ ! -f "setup.py" ]; then
    echo "ERROR: Run this from inside llm-formal-reasoning/"
    exit 1
fi

# ── 1. Updated .gitignore ─────────────────────────────────────────────────────
cat > .gitignore << 'EOF'
# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.env
.venv/
venv/

# Model checkpoints (large — keep on HPC only)
checkpoints/
*.safetensors
*.bin
*.pt
*.pth

# Large data files — tracked selectively below
# zip files ARE tracked (compressed datasets for GitHub)
*.jsonl

# Exceptions — small enough to track directly
!data/finetune/regex_dfa_dataset_val.jsonl
!data/finetune/regex_dfa_dataset_test.jsonl
!data/curriculum/curriculum_val.jsonl
!data/curriculum/curriculum_test.jsonl
!data/adfa/*.jsonl

# macOS
.DS_Store
.AppleDouble
.LSOverride

# Editor
.vscode/
.idea/
*.swp
*.swo
EOF

echo "✓ .gitignore updated"

# ── 2. tot_experiments/README.md ──────────────────────────────────────────────
mkdir -p tot_experiments/example_outputs

cat > tot_experiments/README.md << 'EOF'
# Tree-of-Thought Experiments

DFA construction evaluation using Tree-of-Thought (ToT) prompting (Section 3).
Applied to the 180-problem diagnostic benchmark under two construction strategies:
**intuitive** (no procedural template) and **derivative** (Brzozowski derivatives).

## Files

| File | Description |
|------|-------------|
| `run_experiment_tot.py` | Main ToT experiment runner |
| `example_outputs/cross_consistency_example_output.txt` | Example Cross-Consistency output (Appendix B) |
| `example_outputs/derivative_example_output.json` | Example derivative-based construction output |
| `example_outputs/intuitive_example_output.json` | Example intuitive construction output |

## Prompts

Prompt templates are in `prompts/`:
- `prompts/intuitive_construction.txt` — no procedural template (Appendix G.12)
- `prompts/derivative_construction.txt` — Brzozowski derivative procedure (Appendix G.12)
- `prompts/cross_consistency.txt` — three-task Cross-Consistency Protocol (Appendix G.12)

## ToT configuration (Appendix D.4)

| Parameter | Value |
|-----------|-------|
| Branches | 2 (intuitive + derivative) |
| Depth | 1 (single-shot per branch) |
| Retries | up to 3 per branch on JSON parse failure |
| Temperature | 0.0 |

## Usage

```bash
export OPENAI_API_KEY=...

python tot_experiments/run_experiment_tot.py \
    --model gpt-5.2 \
    --benchmark data/diagnostic/benchmark_180.jsonl \
    --prompt_dir prompts/ \
    --output_dir tot_experiments/results/gpt52
```

## Failure mode rates — Table 1 (% incorrect, I=Intuitive / D=Derivative)

| Mode | GPT-5.2 | Gemini-2.5 | Qwen-7B | Qwen-14B |
|------|---------|-----------|---------|---------|
| P1 Kleene-star | 12/18 | 14/20 | 22/20 | 18/17 |
| P2 Derivative | 5/35 | 6/40 | 6/50 | 5/45 |
| P3 Pre-minimisation | 13/15 | 12/14 | 15/15 | 12/12 |
| P4 Over-acceptance | 27/8 | 25/11 | 35/12 | 30/10 |
| P5 Boundary loss | 15/18 | 16/20 | 22/22 | 18/18 |
| P6 Redundant states | 22/12 | 24/14 | 25/18 | 22/15 |

Key finding: derivative prompting reduces P4 but surfaces P2 as the dominant failure.
EOF

echo "✓ tot_experiments/README.md created"

# ── 3. data/finetune/README.md ────────────────────────────────────────────────
cat > data/finetune/README.md << 'EOF'
# Fine-Tuning Benchmark

Regex-to-DFA fine-tuning dataset introduced in Section 4.
Generated by `src/dataset/generate_dataset.py` with `seed=42`.

## Files

| File | Description |
|------|-------------|
| `regex_dfa_dataset.zip` | Full dataset — all splits, CoT format |
| `regex_dfa_dataset_train.zip` | Training split — ~22,500 examples |
| `regex_dfa_dataset_val.jsonl` | Validation split |
| `regex_dfa_dataset_test.jsonl` | Test split — ~1,000 examples |

## Unzip

```bash
cd data/finetune
unzip regex_dfa_dataset.zip
unzip regex_dfa_dataset_train.zip
```

## Tiers

| Tier | Share | DFA States | Description |
|------|-------|------------|-------------|
| 1 | ~15% | 2 | Direct symbol mapping |
| 2 | ~25% | 2–4 | Kleene star, plus, optional |
| 3 | ~35% | 3–6 | Alternation and branching |
| 4 | ~25% | 4–18 | Full NFA-to-DFA subset construction |

## Evaluation criterion (Appendix E.2.1)

Correct iff: parse succeeds + complete + deterministic + language-equivalent to ground truth
on all strings up to length 6. No partial credit.
EOF

echo "✓ data/finetune/README.md updated"

# ── 4. data/curriculum/README.md ─────────────────────────────────────────────
cat > data/curriculum/README.md << 'EOF'
# Curriculum Phase Datasets

Phase-wise curriculum learning datasets — Section 4.1 (Table 3).
Not used in the main CoT / No-CoT SFT experiments.

## Files

| File | Phase | Content | Purpose |
|------|-------|---------|---------|
| `curriculum_phase1.jsonl` | 1 | Tier 1 | Simple concatenation/union |
| `curriculum_phase2.jsonl` | 2 | Tier 2 | Kleene star, plus, optional |
| `curriculum_phase3.jsonl` | 3 | Tier 3 | Combined operators + branching |
| `curriculum_phase4.jsonl` | 4 | All tiers | Prevent catastrophic forgetting |
| `curriculum_phase5.jsonl` | 5 | Tier 4 | Full subset construction |
| `curriculum_train.jsonl` | — | All | Joint training split |
| `curriculum_val.jsonl` | — | All | Validation split |
| `curriculum_test.jsonl` | — | All | Test split |

Each file: 70% construction examples + 30% theory Q&A in Qwen ChatML format.

## Curriculum orderings (Table 3, 7B model)

| Order | Sequence | Overall | Tier 4 |
|-------|----------|---------|--------|
| Natural | 1→2→3→4→5 | 43.5% | 39.0% |
| Mid-out | 3→2→4→1→5 | 43.5% | 39.0% |
| Hard-first | 5→1→2→3→4 | 39.0% | 34.1% |
| Random | 2→5→1→4→3 | 37.0% | 31.7% |
| Reverse | 5→4→3→2→1 | 26.0% | 29.3% |
| **Joint CoT SFT** | — | **96.5%** | **82.9%** |

No ordering closes the gap to joint SFT.

## Usage

```bash
bash scripts/slurm/launch_all_curriculum.sh 7b
# or single run:
bash scripts/slurm/submit_curriculum_phasewise.sh 7b 1,2,3,4,5 natural
```
EOF

echo "✓ data/curriculum/README.md updated"

# ── 5. data/adfa/README.md ────────────────────────────────────────────────────
cat > data/adfa/README.md << 'EOF'
# ADFA Contrastive Dataset

Contrastive examples and variants for mechanistic analysis — Section 4.2.
Generated from Tier 4 test examples using `src/mechanistic/build_adfa_variants.py`.

## Files

| File | Description |
|------|-------------|
| `contrastive_positives.jsonl` | 243 examples the CoT-trained 7B model answers correctly (label=1) |
| `contrastive_negatives.jsonl` | 42 examples answered incorrectly (label=0) |
| `contrastive_combined.jsonl` | Merged — input to ADS neuron scoring |
| `variants_v1_alphabet_swap.jsonl` | Same DFA structure, symbols renamed |
| `variants_v2_structural_sibling.jsonl` | Different regex, isomorphic DFA |
| `variants_v3_complexity_decoy.jsonl` | Complex-looking regex → trivial 2-state DFA |
| `variants_v4_step_specific.jsonl` | Same example + step-level correctness labels (VGNS) |

## ADFA filter rule

A neuron encodes subset construction only if V3 bleed ratio < 0.5.
Paper finding: lowest observed bleed ratio is **0.73** across all 56,000 candidates.
No neuron specifically encodes the procedure — computation is fully distributed.

## Regenerate

```bash
python src/mechanistic/build_adfa_variants.py \
    --positives_file data/adfa/contrastive_positives.jsonl \
    --output_dir data/adfa
```
EOF

echo "✓ data/adfa/README.md updated"

# ── 6. Commit ─────────────────────────────────────────────────────────────────
git add .
git status

echo ""
echo "Preview above. Committing..."
git commit -m "Update README, gitignore, and all data READMEs to match actual repo structure

- README.md: rewritten to match exact file structure (flat curriculum,
  zip finetune files, tot_experiments/, no results/logs dirs)
- .gitignore: track zip files + small val/test jsonl, ignore large training jsonl
- data/finetune/README.md: updated for zip format
- data/curriculum/README.md: updated for flat phase file structure
- data/adfa/README.md: updated to match exact files present
- tot_experiments/README.md: created with ToT config and Table 1 failure rates"

git push origin main

echo ""
echo "=============================================="
echo "  Done! All changes pushed to GitHub."
echo "=============================================="
